version: '3.8'

services:
  frontend:
    iamge: cyaninn/prod-web-blackpinkinyourarea:frontend.lastest
    container_name: apache-php-server
    volumes: 
      - ./front-end:/var/www/html
    ports:
      - "80:80"

  backend:
    iamge: cyaninn/prod-web-blackpinkinyourarea:backend.lastest
    container_name: python-crawling-server
    volumes: 
      - ./back-end:/home/ubuntu