---
- name: start docker container
  hosts: prod-web-blackpink
  remote_user: root
  gather_facts: false
#df
  tasks:
  - name: Stop old-version web-server container
    community.docker.docker_container:
      name: web-server
      state: stopped
  - name: Stop old-version crawling-server container
    community.docker.docker_container:
      name: crawling-server
      state: stopped

  - name: remove old-version web-server container
    community.docker.docker_container:
      name: web-server
      state: absent
  - name: remove old-version crawling-server container
    community.docker.docker_container:
      name: crawling-server
      state: absent

  - name: running web-server
    command: "docker run -d -it --name web-server -p 80:80 cyaninn/prod-web-blackpinkinyourarea:frontend.latest"

  - name: running python-server
    command: "docker run -d -it --name crawling-server cyaninn/prod-web-blackpinkinyourarea:backend.latest"