---
- name: start docker container
  hosts: prod-web-blackpink
  remote_user: root

  tasks:
  #- name: stop and remove old version container
  #  command: "docker stop web-server && docker rm web-server"
  #  command: "docker stop crawling-server && docker rm crawling-server"

  - name: running web-server
    command: "docker run -d -it --name web-server -p 80:80 cyaninn/prod-web-blackpinkinyourarea:frontend.latest"

  - name: running python-server
    command: "docker run -d -it --name crawling-server cyaninn/prod-web-blackpinkinyourarea:backend.latest"